#!/bin/sh

set -e
ANSI_RED='\033[0;31m'
ANSI_GREEN='\033[0;32m'
ANSI_YELLOW='\033[1;33m'
ANSI_RESET='\033[0m'

PACKAGE_NAME=grasp
INSTALL_DIR=grasp

PATH_PROJECT=/var/www/${INSTALL_DIR}
PATH_CONFIG=/etc/grasp/

FLAG_CONFIG="0"

PHP_VERSIONS=$(ps -e -o stat,command | grep -E '^Ss\s+php-fpm' | grep -E '[0-9]+\.[0-9]+' -o)

case "$1" in
    configure)
        echo "\n ${ANSI_YELLOW} Running GRASP post-install... ${ANSI_RESET} \n"

        mkdir -p ${PATH_PROJECT}/cache
        mkdir -p ${PATH_PROJECT}/logs

        echo -n "Checking ETC Configs ..."
        if [ -e "${PATH_CONFIG}/main.ini" ]; then
            echo "${PATH_CONFIG}/main.ini ${ANSI_GREEN} FOUND ${ANSI_RESET}";
            FLAG_CONFIG="+";
        else
            echo "${PATH_CONFIG}/main.ini ${ANSI_RED} NOT FOUND! ${ANSI_RESET}" ;
        fi

        echo

        echo " Clearing SMARTY cache"
        rm -f ${PATH_PROJECT}/cache/*
        echo "  Ok"

        echo "Fixing access rights..."
        chown -R www-data:www-data ${PATH_PROJECT}/*
        echo "${ANSI_GREEN} Ok. ${ANSI_RESET}"

        echo
        echo "Restarting all running php-fpm processes..."
        for version in $PHP_VERSIONS; do echo "Restarting ${ANSI_YELLOW}php${version}-fpm${ANSI_RESET} process..."; systemctl restart php${version}-fpm; done
        echo "${ANSI_GREEN}Finished.${ANSI_RESET}"

        echo
        echo "${ANSI_YELLOW} ... post-install finished. ${ANSI_RESET}"
        echo

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
